name: ice-userbot
selector:
  app.kubernetes.io/part-of: vote
  app.kubernetes.io/component: api
image: python:3
command: ["python3", "-m userbot"]
workdir: /home/iceuserbot/
sync:
 - .: /home/iceuserbot/
environment:
  - STRING_SESSION=$STRING_SESSION
  - API_KEY=$API_KEY
  - API_HASH=$API_HASH
  - BOT_TOKEN=$BOT_TOKEN
  - BOT_USERNAME=$BOT_USERNAME
  - BOTLOG_CHATID=$BOTLOG_CHATID
  - DATABASE_URL=$DATABASE_URL
  - PM_AUTO_BAN=$PM_AUTO_BAN
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
forward:
  - 8080:80
  - 5432:postgres:5432
reverse:
  - 9000:9001
securityContext:
  runAsUser: 1000
  runAsGroup: 2000
  fsGroup: 3000
  capabilities:
    add:
    - SYS_PTRACE